### ISSUE TITLE
Other providers?

### ISSUE THREAD

**Issue by aptonline** [maddox/pluto-for-channels#10]
Hi, I appreciate this is a solution for Pluto.tv but it strikes me that this could also be used to help with other providers, especially if you have more than the 500 channel limit that's currently in place with Channels.

Would it be possible to develop it (or a separate branch) so you can feed in a custom m3u and xml file that is then parsed correctly for Channels.  It would also be useful to have the ability to target a specific group in the m3u to get around the 500 channel limit.

Thanks

**Comment by tmm1** [comment]
This is out of scope for this project. The goal here is simply to serve as an example of what's possible with Custom Channels integration. You're free to develop your own projects using this as an example.

**Comment by maddox** [comment]
I think what you're looking for is something like http://m3u4u.com/

There are lots of projects out there that let you feed it an M3U and will let you filter it down to something more usable.

**Comment by aptonline** [comment]
Thanks for the consideration but it was more about adding the improved Channels specific content which interested me, the splitting channel up by groups was an added bonus.

I still believe there is value is such a solution so I may have a poke around in the code 😀.
