### ISSUE TITLE
Vevo 2K no longer appearing

### ISSUE THREAD

**Issue by Fofer** [maddox/pluto-for-channels#14]
Up until a few days ago, I was able to watch and record Pluto TV's channel "Vevo 2k" in the Channels app, by way of this Docker.  Now that channel is no longer showing.    

Thanks for any updates or info.  Much appreciated!

**Comment by maddox** [comment]
Vevo 2K is appearing for me. Be sure you're on the latest and bounce the container if you need to. 

Load your playlist URL and you'll see Vevo 2K is in there.
