### ISSUE TITLE
empty sub-title causes formatting problems

### ISSUE THREAD

**Issue by john9527** [maddox/pluto-for-channels#2]
Using the shorthand for an empty sub-title in epg.xml
`<sub-title lang="en"/>`
can cause formatting problems in the timeline display (not sure what you are calling this) when the stream is playing.  The show name partially overlays the timeline.

Can be corrected by using the full version
`<sub-title lang="en"> </sub-title>`

**Comment by maddox** [comment]
Can you send a screenshot?

**Comment by john9527** [comment]
This can be closed.  WIth the latest epg.xml updates the problem has no longer occurred.
