### ISSUE TITLE
Copying URL into Firestick

### ISSUE THREAD

**Issue by Rene123** [maddox/pluto-for-channels#30]
I got to this place after PlutoTV stopped working by mjh site. And now tried to copy the playlist.m3u into tvmate on my firestick, But it keeps telling me that it is not working.

When i move the m3u to local network and try to load it, there is no problem. I used the previous Pluto from an URL too and was no problem.

Anyone know what is the problem?

**Comment by maddox** [comment]
This project simply exposes an m3u file via a URL. 

It’s possible the issue is with your home networking or routing in general (firewall), which is outside the scope of this project. 

If it’s not working in TVMate, you should contact them as it’s an issue with that particular application.
