### ISSUE TITLE
Can't update to 1.0.18

### ISSUE THREAD

**Issue by mikesalz** [maddox/pluto-for-channels#6]
This is probably just me being dumb, but I am unable to update to Synology docker container to v1.0.18.

I have the latest image: (I have actually tried :latest as well as :1.0.18)
![image](https://user-images.githubusercontent.com/46855061/103245855-8050c680-492f-11eb-97e9-6255652d9fbe.png)

`
`

And my container is using :latest. I have tried clearing the container and ever completely removing and recreating it
![image](https://user-images.githubusercontent.com/46855061/103245892-952d5a00-492f-11eb-9163-6c210a823b97.png)

`
`

But no matter what I do, it still thinks I have v1.0.17
![image](https://user-images.githubusercontent.com/46855061/103246037-0bca5780-4930-11eb-952b-ddf00fa012e1.png)

`
`

Please tell me what stupid thing I am doing here!

**Comment by tmm1** [comment]
Looks like the VERSION file was not bumped: https://github.com/maddox/pluto-for-channels/blob/main/VERSION

So you are running the latest version, but it is confused and doesn't realize that.

**Comment by maddox** [comment]
I just fixed this and it's rolling out now.

**Comment by mikesalz** [comment]
@maddox @tmm1  Wait... So I'm NOT stupid??? :)

Thank you, gentlemen!
