### ISSUE TITLE
Minor issue in 1.0.18 reaching index.html

### ISSUE THREAD

**Issue by kcook98765** [maddox/pluto-for-channels#7]
Hi,
Been running 1.0.17 for a couple weeks with no real issues.

I just upgraded to 1.0.18 on my qnap.

I had to of course use a different port (8282) as qnap uses 8080 . and all seems fine with one minor glitch:

Calling the url:

http://192.168.2.102:8282

Brings up the generic NGINX welcome page, I had to append /index.html to see the status page.

So not a major issue, but thought you'd like to know.

**Comment by tmm1** [comment]
This can happen while the docker is booting and files have not been generated yet.
